apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocis-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ocis-test
    repoURL: https://github.com/grischdian/ochstest
    targetRevision: HEAD

