apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tika	
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    chart: tika
    repoURL: https://apache.jfrog.io/artifactory/tika
    targetRevision: 2.9.0
    helm:
      releaseName: tika
      values: |
        image:
          tag: "latest-full"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tika
