apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wopi
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    chart: wopiserver
    repoURL: https://cs3org.github.io/charts/
    targetRevision: 0.9.2
    helm: 
      releaseName: wopiserver
      values: |
        image:
          tag: v10.4.0
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: issuer
            kubernetes.io/ingress.class: nginx
          hostname: wopi.rost.cloud
          tls:
            - secretName: wopi-tls
              hosts:
              - wopi.rost.cloud
        config:
          cs3:
            gateway: gateway.ocis.svc.cluster.local:9142
            sslVerify: False
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wopiserver
